---
- hosts: all
  tasks:
    - name: install httpd
      package: name=httpd state=installed
    - name: configure
      command: echo hello >> /var/www/html/index.html
    - name: start service
      service: name=httpd state=started
